### ISSUE TITLE
Convert to kramdown

### ISSUE THREAD

**Issue by johnelse** [xapi-project/xapi-project.github.io#189]
Github pages is going to stop supporting redcarpet (see [here](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/)) so we need to switch to Kramdown. This can be done by editing the `markdown` line of `_config.yml`.

[here](http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/) are some notes about getting kramdown to support github-flavoured markdown.

**Comment by robhoes** [comment]
Fixed by #196
