### ISSUE TITLE
Incorrect hyperlinks for usb items in 7.3 release file.

### ISSUE THREAD

**Issue by ringods** [xapi-project/xapi-project.github.io#228]
This file contains a number of incorrect hyperlinks:

https://xapi-project.github.io/xen-api/releases/inverness.html

All links related to `PUSB`, `VUSB` and `USB_group` classes & fields point to the URL above, so to itself.

The following class documentation does not seem to exist:

https://xapi-project.github.io/xen-api/classes/pusb.html
https://xapi-project.github.io/xen-api/classes/vusb.html
https://xapi-project.github.io/xen-api/classes/usb_group.html

**Comment by gaborigloi** [comment]
Thanks for reporting the issue! It has been fixed and the above classes now appear in the docs.
