### ISSUE TITLE
Upgrade to bootstrap 3

### ISSUE THREAD

**Issue by simonjbeaumont** [xapi-project/xapi-project.github.io#38]
The site that this was forked from uses bootstrap 2.3.2.

There are steps published for the migration from 2.x to 3 here:

http://getbootstrap.com/migration/

However, this site unfortunately makes use of the classes in the "What's removed" section. This section has no equivalent so it's not a simple sed operation.

Would be good to do though so we can maintain this site easier as time goes on.

**Comment by robhoes** [comment]
Done a while ago.
