### ISSUE TITLE
Split "Using HTTP to interact with XenServer" into two

### ISSUE THREAD

**Issue by djs55** [xapi-project/xapi-project.github.io#56]
Currently the page contains

- VM import and export
- Getting Xenserver performance stats

I think these should both be top-level items under the XenAPI section, People will look at this by talk rather ("how do I import?") rather than by protocol ("what can I do with HTTP?")

(Do you agree @robhoes?)

**Comment by djs55** [comment]
oh actually same argument applies to "XenServer API extensions"

- consoles
- installing from templates
- xenstore entries
- network stuff
- XenCenter tweaks: internationalisation and hiding objects

**Comment by robhoes** [comment]
Yes indeed. I think this content should be reorganised a bit, and grouped by logical part of the XenAPI, such as VM lifecycle operations, import/export, consoles, stats, networking, storage etc.
